server:
  port: 8084

spring:
  application:
    name: notification-service

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone : http://127.0.0.1:8080/eureka/