server:
  port: 8012

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
          gateway.route.RouteDefinitionLocator: INFO

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
      # Auth Service Route
      - id: Auth-Service
        uri: lb://Auth-Service
        predicates:
          - Path=/auth/**
      # Behavior Analysis Service Route
      - id: behavior-analysis-service
        uri: lb://behavior-analysis-service
        predicates:
          - Path=/api/behaviroal-analys
      # Notification Service Route
      - id: notification-service
        uri: lb://notification-service
        predicates:
          - Path=/api/notification
      # Rules Service Route
      - id: rules-service
        uri: lb://transaction-fraud
        predicates:
          - Path=/api/v1/transaction-fraud
      # Transaction Monitoring Service Route
#      - id: transaction-monitoring-service
#        uri: lb://transaction-monitoring-service
#        predicates:
#          - Path=/
      # Transaction Service Route
      - id: Transaction-Service
        uri: lb://Transaction-Service
        predicates:
          - Path=/api/v1/transaction
      # User Service Route
      - id: user-service
        uri: lb://user-service
        predicates:
          - Path=/api/v1/user/**
      # Discovery Server Route
      - id: discovery-service
        uri: http://localhost:8080
        predicates:
        - Path=/eureka/web
        filters:
        - SetPath=/
      # Discovery Server Static Resources Route
      - id: discovery-service-static
        uri: http://localhost:8080
        predicates:
        - Path=/eureka/**
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri=http://localhost:8180/auth/realms/ticket-digi-realm:
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      probability: 1.0

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always