server:
  port: 8012

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
          gateway.route.RouteDefinitionLocator: INFO

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
      # User Service Route
      - id: user-service
        uri: lb://booking-service
        predicates:
        - Path=/api/v1/bookings/**

  
      # Discovery Server Route
      - id: discovery-service
        uri: http://localhost:8761
        predicates:
        - Path=/eureka/web
        filters:
        - SetPath=/
      # Discovery Server Static Resources Route
      - id: discovery-service-static
        uri: http://localhost:8761
        predicates:
        - Path=/eureka/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri=http://localhost:8180/auth/realms/ticket-digi-realm:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0