server:
  port: 8085

spring:
  application:
    name: behavior-analysis-service

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone : http://127.0.0.1:8080/eureka/